class ProductItem {
  static List<Map<String, dynamic>> productItem = [
    {
      'id': 1,
      'count': 1,
      'productName': 'Apple',
      'price': 10.0,
      'quantity': 30,
    },
    {
      'id': 2,
      'count': 1,
      'productName': 'Banana',
      'price': 5.0,
      'quantity': 50,
    },
    {
      'id': 3,
      'count': 1,
      'productName': 'Orange',
      'price': 8.0,
      'quantity': 40,
    },
    {
      'id': 4,
      'count': 1,
      'productName': 'Meat',
      'price': 1500.0,
      'quantity': 5,
    },
    {
      'id': 5,
      'count': 1,
      'productName': 'Chicken',
      'price': 200.0,
      'quantity': 20,
    },
    {
      'id': 6,
      'count': 1,
      'productName': 'Milk',
      'price': 3.0,
      'quantity': 100,
    },
    {
      'id': 7,
      'count': 1,
      'productName': 'Bread',
      'price': 1.5,
      'quantity': 15,
    },
    {
      'id': 8,
      'count': 1,
      'productName': 'Cheese',
      'price': 50.0,
      'quantity': 10,
    },
    {
      'id': 9,
      'count': 1,
      'productName': 'Tomato',
      'price': 12.0,
      'quantity': 25,
    },
    {
      'id': 10,
      'count': 1,
      'productName': 'Potato',
      'price': 7.0,
      'quantity': 60,
    },
    {
      'id': 11,
      'count': 1,
      'productName': 'Onion',
      'price': 6.0,
      'quantity': 45,
    },
    {
      'id': 12,
      'count': 1,
      'productName': 'Carrot',
      'price': 4.0,
      'quantity': 35,
    },
    {
      'id': 13,
      'count': 1,
      'productName': 'Cucumber',
      'price': 3.0,
      'quantity': 50,
    },
    {
      'id': 14,
      'count': 1,
      'productName': 'Lettuce',
      'price': 2.5,
      'quantity': 20,
    },
    {
      'id': 15,
      'count': 1,
      'productName': 'Garlic',
      'price': 10.0,
      'quantity': 15,
    },
    {
      'id': 16,
      'count': 1,
      'productName': 'Egg',
      'price': 0.2,
      'quantity': 200,
    },
    {
      'id': 17,
      'count': 1,
      'productName': 'Pork',
      'price': 180.0,
      'quantity': 8,
    },
    {
      'id': 18,
      'count': 1,
      'productName': 'Fish',
      'price': 250.0,
      'quantity': 12,
    },
    {
      'id': 19,
      'count': 1,
      'productName': 'Rice',
      'price': 40.0,
      'quantity': 30,
    },
    {
      'id': 20,
      'count': 1,
      'productName': 'Beans',
      'price': 15.0,
      'quantity': 40,
    },
    {
      'id': 21,
      'count': 1,
      'productName': 'Dumble',
      'price': 2000.33,
      'quantity': 12,
    },
    {
      'id': 22,
      'count': 1,
      'productName': 'HeavyDumble',
      'price': 200.33,
      'quantity': 13,
    },
    {
      'id': 23,
      'count': 1,
      'productName': 'Sugar',
      'price': 1500000.0,
      'quantity': 7,
    },
    {
      'id': 24,
      'count': 1,
      'productName': 'Meat',
      'price': 1500.0,
      'quantity': 5,
    }
  ];
}
